//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentMigrator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentMigrator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures, Processes &amp; Reports.
        /// </summary>
        internal static string destDocLibName {
            get {
                return ResourceManager.GetString("destDocLibName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://colibanwater.sharepoint.com/teams/LendLease.
        /// </summary>
        internal static string destSCUrl {
            get {
                return ResourceManager.GetString("destSCUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://colibanwater.sharepoint.com/teams/LendLease/.
        /// </summary>
        internal static string destWebUrl {
            get {
                return ResourceManager.GetString("destWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures, Processes &amp; Reports.
        /// </summary>
        internal static string sourceDocLibName {
            get {
                return ResourceManager.GetString("sourceDocLibName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://epm.coliban.com.au/PWA.
        /// </summary>
        internal static string sourceSCUrl {
            get {
                return ResourceManager.GetString("sourceSCUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6D213869-A2B4-46A5-92C3-EFA7B1EB5FFE.
        /// </summary>
        internal static string sourceViewId {
            get {
                return ResourceManager.GetString("sourceViewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://epm.coliban.com.au/PWA/LendLease/.
        /// </summary>
        internal static string sourceWebUrl {
            get {
                return ResourceManager.GetString("sourceWebUrl", resourceCulture);
            }
        }
    }
}
